# Generated by Django 4.2.11 on 2025-01-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('protocol', models.TextField(null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer', models.TextField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_module', models.CharField(blank=True, max_length=50, null=True)),
                ('process_id', models.PositiveIntegerField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apache Log',
                'verbose_name_plural': 'Apache Logs',
            },
        ),
        migrations.CreateModel(
            name='ApacheLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='apache', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/apache/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='token1', max_length=255)),
            ],
            bases=('authtoken.token',),
        ),
        migrations.CreateModel(
            name='IISLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='iis', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/iis/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinuxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=255, null=True)),
                ('event', models.TextField(max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('log_level', models.CharField(max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Linux Log',
                'verbose_name_plural': 'Linux Logs',
            },
        ),
        migrations.CreateModel(
            name='LinuxLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='Linux', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/linux/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='mac', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/mac/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MongoLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='mongo', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/mongo/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MysqlLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='mysql', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/mysql/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('protocol', models.TextField(null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer', models.TextField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_module', models.CharField(blank=True, max_length=50, null=True)),
                ('process_id', models.PositiveIntegerField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nginx Log',
                'verbose_name_plural': 'Nginx Logs',
            },
        ),
        migrations.CreateModel(
            name='NginxLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='nginx', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/nginx/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgresLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='postgres', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/postgres/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindowsADLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('os_type', models.CharField(default='WindowsAD', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/windowsAD/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindowsLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(default='Windows', max_length=255)),
                ('os_type', models.CharField(default='Windows', max_length=50)),
                ('file', models.FileField(upload_to='uploaded_logs/windows/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeCreated', models.DateTimeField()),
                ('event_id', models.IntegerField()),
                ('LevelDisplayName', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
                ('message', models.TextField(null=True)),
                ('severity', models.CharField(default='None', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
