# Generated by Django 4.2.11 on 2025-01-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0002_delete_apachelogfile_alter_apachelog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheSourceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='apachelog',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='log_management_app.apachesourceinfo'),
        ),
    ]
