# Generated by Django 4.2.11 on 2025-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0004_remove_apachelog_source_delete_apachesourceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='timestamp',
            field=models.CharField(null=True),
        ),
    ]
