# Generated by Django 4.2.11 on 2025-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0005_alter_apachelog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='log_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='request_line',
            field=models.CharField(blank=True, default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='response_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='timestamp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
