# Generated by Django 4.2.11 on 2025-01-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0006_apachelog_error_message_apachelog_log_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachelog',
            name='log_type',
            field=models.CharField(choices=[('access', 'Access'), ('error', 'Error')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
