# Generated by Django 4.2.11 on 2025-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0007_apachelog_log_type_alter_apachelog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apachelog',
            name='log_type',
        ),
        migrations.AlterField(
            model_name='apachelog',
            name='timestamp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
