# Generated by Django 4.2.11 on 2025-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0008_remove_apachelog_log_type_alter_apachelog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachelog',
            name='log_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
