# Generated by Django 4.2.11 on 2025-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0009_apachelog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apachelog',
            name='log_type',
            field=models.CharField(choices=[('access', 'Access'), ('error', 'Error')], max_length=50, null=True),
        ),
    ]
