# Generated by Django 4.2.11 on 2025-01-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0010_alter_apachelog_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apachelog',
            name='thread_id',
        ),
    ]
