# Generated by Django 4.2.11 on 2025-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0011_remove_apachelog_thread_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linuxlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Linux Log', 'verbose_name_plural': 'Linux Logs'},
        ),
        migrations.RenameField(
            model_name='linuxlog',
            old_name='process',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='linuxlog',
            old_name='source',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='linuxlog',
            old_name='username',
            new_name='session_status',
        ),
        migrations.RemoveField(
            model_name='linuxlog',
            name='event',
        ),
        migrations.RemoveField(
            model_name='linuxlog',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='linuxlog',
            name='status',
        ),
        migrations.AddField(
            model_name='linuxlog',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linuxlog',
            name='log_type',
            field=models.CharField(choices=[('syslog', 'Syslog'), ('authlog', 'Authlog')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='linuxlog',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linuxlog',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linuxlog',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linuxlog',
            name='log_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linuxlog',
            name='timestamp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
