# Generated by Django 4.2.11 on 2025-01-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0012_alter_linuxlog_options_rename_process_linuxlog_pwd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nginxlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Nginx Log', 'verbose_name_plural': 'Nginx Logs'},
        ),
        migrations.RenameField(
            model_name='nginxlog',
            old_name='error_module',
            new_name='log_level',
        ),
        migrations.RemoveField(
            model_name='nginxlog',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='nginxlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='nginxlog',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='nginxlog',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='nginxlog',
            name='url',
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='log_type',
            field=models.CharField(choices=[('access', 'Access'), ('error', 'Error')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='remote_logname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='remote_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='request_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nginxlog',
            name='response_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlog',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlog',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlog',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlog',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nginxlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
