# Generated by Django 4.2.11 on 2025-01-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0013_alter_nginxlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='Low', max_length=10),
        ),
    ]
