# Generated by Django 4.2.11 on 2025-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0015_rename_host_alert_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_title',
            field=models.CharField(max_length=100),
        ),
    ]
