# Generated by Django 4.2.11 on 2025-01-25 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management_app', '0017_alter_alert_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=255)),
                ('event_id', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('level', models.CharField(max_length=50)),
                ('log_user', models.CharField(max_length=255)),
                ('computer', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.DeleteModel(
            name='WindowsLogFile',
        ),
    ]
