# Generated by Django 4.2.11 on 2025-01-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0018_windowslog_alter_alert_options_delete_windowslogfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxlog',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
