# Generated by Django 4.2.11 on 2025-01-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management_app', '0019_linuxlog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linuxlog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linux_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
