# Generated by Django 4.2.11 on 2025-01-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0020_alter_linuxlog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxlog',
            name='log_source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
