# Generated by Django 4.2.11 on 2025-01-28 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management_app', '0021_linuxlog_log_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachelog',
            name='log_source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apachelog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apache_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
