# Generated by Django 4.2.11 on 2025-01-29 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management_app', '0022_apachelog_log_source_name_apachelog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_source_name', models.CharField(max_length=255)),
                ('log_type', models.CharField(default='mysql_error', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('process_id', models.IntegerField()),
                ('log_level', models.CharField(blank=True, choices=[('System', 'System'), ('Warning', 'Warning'), ('Error', 'Error'), ('Info', 'Info')], max_length=20, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysql_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NginxLog',
        ),
    ]
