# Generated by Django 4.2.11 on 2025-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0023_mysqllog_delete_nginxlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysqllog',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='mysqllog',
            name='log_level',
        ),
        migrations.RemoveField(
            model_name='mysqllog',
            name='process_id',
        ),
    ]
