# Generated by Django 4.2.11 on 2025-01-29 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management_app', '0024_remove_mysqllog_error_code_remove_mysqllog_log_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_source_name', models.CharField(max_length=255)),
                ('log_type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redis_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
