# Generated by Django 4.2.11 on 2025-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0025_redislog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redislog',
            name='log_type',
            field=models.CharField(default='redis', max_length=50),
        ),
    ]
