# Generated by Django 4.2.11 on 2025-01-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0026_alter_redislog_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='Low', max_length=100),
        ),
    ]
