# Generated by Django 4.2.11 on 2025-02-01 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_management_app', '0027_alter_alert_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowsADLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windowsAD_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LinuxLogFile',
        ),
        migrations.DeleteModel(
            name='WindowsADLogFile',
        ),
        migrations.RemoveField(
            model_name='windowslog',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='windowslog',
            name='level',
        ),
        migrations.RemoveField(
            model_name='windowslog',
            name='log_name',
        ),
        migrations.RemoveField(
            model_name='windowslog',
            name='log_user',
        ),
        migrations.RemoveField(
            model_name='windowslog',
            name='source',
        ),
        migrations.AddField(
            model_name='windowslog',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='windowslog',
            name='log_source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='windowslog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
