# Generated by Django 4.2.11 on 2025-02-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0029_delete_maclogfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windowslog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
