# Generated by Django 5.1.5 on 2025-02-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0030_linuxlog_processed_windowslog_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxlog',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='linuxlog',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
