# Generated by Django 5.1.5 on 2025-02-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0033_alter_linuxlog_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsadlog',
            name='log_type',
            field=models.CharField(blank=True, choices=[('syslog', 'Syslog'), ('authlog', 'Authlog')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='windowslog',
            name='log_type',
            field=models.CharField(blank=True, choices=[('syslog', 'Syslog'), ('authlog', 'Authlog')], max_length=50, null=True),
        ),
    ]
