# Generated by Django 5.1.5 on 2025-02-14 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0034_windowsadlog_log_type_windowslog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='linux_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_management_app.linuxlog'),
        ),
        migrations.AddField(
            model_name='alert',
            name='windows_ad_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_management_app.windowsadlog'),
        ),
        migrations.AddField(
            model_name='alert',
            name='windows_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_management_app.windowslog'),
        ),
    ]
