# Generated by Django 5.1.5 on 2025-02-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('log_management_app', '0035_alert_linux_log_alert_windows_ad_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='linux_log',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='windows_ad_log',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='windows_log',
        ),
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='alert',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
