# Generated by Django 5.1.5 on 2025-02-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0036_remove_alert_linux_log_remove_alert_windows_ad_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='object_id',
        ),
        migrations.AddField(
            model_name='alert',
            name='log_source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
