# Generated by Django 5.1.5 on 2025-02-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0037_remove_alert_content_type_remove_alert_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='log_source_name',
        ),
    ]
