# Generated by Django 5.1.5 on 2025-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0038_remove_alert_log_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='log_source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
