# Generated by Django 5.1.5 on 2025-02-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0040_alert_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowsadlog',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
