# Generated by Django 5.1.5 on 2025-02-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0042_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='report_title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='data_source',
        ),
        migrations.AddField(
            model_name='report',
            name='data_sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='log_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
