# Generated by Django 5.1.5 on 2025-03-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0043_rename_title_report_report_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apachelog',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customtoken',
            name='token_ptr',
        ),
        migrations.DeleteModel(
            name='IISLogFile',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='MongoLogFile',
        ),
        migrations.RemoveField(
            model_name='mysqllog',
            name='owner',
        ),
        migrations.DeleteModel(
            name='MysqlLogFile',
        ),
        migrations.DeleteModel(
            name='NginxLogFile',
        ),
        migrations.DeleteModel(
            name='PostgresLogFile',
        ),
        migrations.RemoveField(
            model_name='redislog',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ApacheLog',
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.DeleteModel(
            name='MysqlLog',
        ),
        migrations.DeleteModel(
            name='RedisLog',
        ),
    ]
