# Generated by Django 5.1.2 on 2024-11-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('log_management_app', '0110_delete_processlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='alert',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
