# Generated by Django 5.1.2 on 2024-11-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0111_alert_content_type_alert_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='object_id',
        ),
    ]
