# Generated by Django 4.2.17 on 2024-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0113_alter_alert_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('hostname', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('source_ip', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=50)),
                ('log_level', models.CharField(max_length=50)),
                ('process', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Linux Log',
                'verbose_name_plural': 'Linux Logs',
            },
        ),
    ]
