# Generated by Django 4.2.17 on 2024-12-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0116_alter_linuxlog_event_alter_linuxlog_hostname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linuxlog',
            name='user',
        ),
    ]
