# Generated by Django 4.2.17 on 2024-12-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0117_remove_linuxlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linuxlog',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='linuxlog',
            name='username',
        ),
    ]
