# Generated by Django 4.2.17 on 2024-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0118_remove_linuxlog_source_ip_remove_linuxlog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxlog',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linuxlog',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
