# Generated by Django 4.2.17 on 2024-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0119_linuxlog_source_ip_linuxlog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linuxlog',
            name='event',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linuxlog',
            name='log_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linuxlog',
            name='source_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='linuxlog',
            name='timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
