# Generated by Django 4.2.17 on 2024-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management_app', '0120_alter_linuxlog_event_alter_linuxlog_log_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('protocol', models.TextField(null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('referrer', models.TextField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_module', models.CharField(blank=True, max_length=50, null=True)),
                ('process_id', models.PositiveIntegerField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apache Log',
                'verbose_name_plural': 'Apache Logs',
            },
        ),
        migrations.DeleteModel(
            name='ApacheLogFile',
        ),
    ]
