# Generated by Django 4.2.17 on 2024-12-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('log_management_app', '0123_apachelogfile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='token1', max_length=255)),
            ],
            bases=('authtoken.token',),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
